# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  passManger_config = debug
endif
ifeq ($(config),release)
  passManger_config = release
endif
ifeq ($(config),dist)
  passManger_config = dist
endif

PROJECTS := passManger

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

passManger:
ifneq (,$(passManger_config))
	@echo "==== Building passManger ($(passManger_config)) ===="
	@${MAKE} --no-print-directory -C passManger -f Makefile config=$(passManger_config)
endif

clean:
	@${MAKE} --no-print-directory -C passManger -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   passManger"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"